import Head from "next/head";
import Image from "next/image";

import Main from "../components/Main landing page/Main";
import Footer from "../components/Main landing page/Footer";
import Imageslider from "../components/Main landing page/Imageslider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Not Just App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      
        <Imageslider />
        <Main/>
        <Footer/>
    </>
  );
}
